name = "glenstack-com"
type = "webpack"
account_id = "41d154df19739a540756d193a9715370"
workers_dev = true
# route = "glenstack.com/*"
# zone_id = "1a50aad2a97cd8ee713df553f2214779"

[site]
bucket = "./public"
entry-point = "worker"
