name = "glenstack-ui"
type = "webpack"
account_id = "41d154df19739a540756d193a9715370"
route = "*ui.glenstack.dev/*"
zone_id = "b871929efc74ff6123beaff3a5f55841"

[site]
bucket = "./storybook-static"
entry-point = "workers-site"
